#! /usr/bin/env python3

import sys

class Consts:
    HERE = 10
    LATEST = 12
    DICT = 0xFEFE
    AREA = DICT + 2

    iHERE = 0
    iLATEST = 1

class PrimOpcodes:
    NOP = 0x00
    CALL = 0x01
    JP = 0x02
    JZ = 0x03
    AND = 0x04
    OR = 0x05
    XOR = 0x06
    NOT = 0x07
    SR = 0x08
    SRW = 0x9
    SL = 0x0a
    SLW = 0x0b
    ADD = 0x0c
    SUB = 0x0d
    LTS = 0x0e
    LTU = 0x0f
    SWAP = 0x10
    OVER = 0x11
    DUP = 0x12
    NIP = 0x13
    ROT = 0x14
    NROT = 0x15
    DROP = 0x16
    RDROP = 0x17
    CARRY = 0x18
    TO_R = 0x19
    FROM_R = 0x1a
    INT = 0x1b
    FETCH = 0x1c
    BYTE_FETCH = 0x1d
    STORE = 0x1e
    BYTE_STORE = 0x1f
    PUSH8  = 0x20
    PUSH = 0x21
    BREAK = 0x22
    SIMEND = 0xff


def export_opcodes(fn):
    opcodes = [it for it in vars(PrimOpcodes).items() if not it[0].startswith("__")]
    content = [f"// this file is autogenerated\n", "\n", "localparam\n"]
    for op in opcodes[0:-1]:
        content += f"    OP_{op[0]} = 7'h{op[1]:02x},\n"
    content += f"    OP_{opcodes[-1][0]} = 7'h{opcodes[-1][1]:02x};\n"
    with open(fn, "wt") as f:
        f.writelines(content)
    

if __name__ == "__main__":
    fn = "opcodes.v" if len(sys.argv) == 1 else sys.argv[1]
    export_opcodes(fn)
